/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
	"context"
	"net/http"
	"net/url"
	"strings"
)

// Linger please
var (
	_ context.Context
)

type LiveStreamApiGetLiveStreamKeysRequest struct {
	search  *string
	sortBy  *string
	orderBy *string
	offset  *int32
	limit   *int32
}

func (r LiveStreamApiGetLiveStreamKeysRequest) Search(search string) LiveStreamApiGetLiveStreamKeysRequest {
	r.search = &search
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) SortBy(sortBy string) LiveStreamApiGetLiveStreamKeysRequest {
	r.sortBy = &sortBy
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) OrderBy(orderBy string) LiveStreamApiGetLiveStreamKeysRequest {
	r.orderBy = &orderBy
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) Offset(offset int32) LiveStreamApiGetLiveStreamKeysRequest {
	r.offset = &offset
	return r
}
func (r LiveStreamApiGetLiveStreamKeysRequest) Limit(limit int32) LiveStreamApiGetLiveStreamKeysRequest {
	r.limit = &limit
	return r
}

type LiveStreamServiceI interface {
	/*
	 * CreateLiveStreamKey Create live stream key
	 * @return LiveStreamApiCreateLiveStreamKeyRequest
	 */

	CreateLiveStreamKey(input CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error)

	/*
	 * CreateLiveStreamKey Create live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return LiveStreamApiCreateLiveStreamKeyRequest
	 */

	CreateLiveStreamKeyWithContext(ctx context.Context, input CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error)

	/*
	 * CreateStreaming Create a new live stream video
	 * @param id Live stream key ID
	 * @return LiveStreamApiCreateStreamingRequest
	 */

	CreateStreaming(id string, input CreateStreamingRequest) (*CreateStreamingResponse, error)

	/*
	 * CreateStreaming Create a new live stream video
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiCreateStreamingRequest
	 */

	CreateStreamingWithContext(ctx context.Context, id string, input CreateStreamingRequest) (*CreateStreamingResponse, error)

	/*
	 * DeleteLiveStreamKey Delete live stream key
	 * @param id Live stream key ID
	 * @return LiveStreamApiDeleteLiveStreamKeyRequest
	 */

	DeleteLiveStreamKey(id string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamKey Delete live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiDeleteLiveStreamKeyRequest
	 */

	DeleteLiveStreamKeyWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamVideo Delete live stream video
	 * @param id Live stream video ID
	 * @return LiveStreamApiDeleteLiveStreamVideoRequest
	 */

	DeleteLiveStreamVideo(id string) (*ResponseSuccess, error)

	/*
	 * DeleteLiveStreamVideo Delete live stream video
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream video ID
	 * @return LiveStreamApiDeleteLiveStreamVideoRequest
	 */

	DeleteLiveStreamVideoWithContext(ctx context.Context, id string) (*ResponseSuccess, error)

	/*
	 * GetLiveStreamKey Get live stream key
	 * @param id ID
	 * @return LiveStreamApiGetLiveStreamKeyRequest
	 */

	GetLiveStreamKey(id string) (*GetLiveStreamKeyResponse, error)

	/*
	 * GetLiveStreamKey Get live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id ID
	 * @return LiveStreamApiGetLiveStreamKeyRequest
	 */

	GetLiveStreamKeyWithContext(ctx context.Context, id string) (*GetLiveStreamKeyResponse, error)

	/*
	 * GetLiveStreamKeys Get live stream key list
	 * @return LiveStreamApiGetLiveStreamKeysRequest
	 */

	GetLiveStreamKeys(r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error)

	/*
	 * GetLiveStreamKeys Get live stream key list
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @return LiveStreamApiGetLiveStreamKeysRequest
	 */

	GetLiveStreamKeysWithContext(ctx context.Context, r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error)

	/*
	 * GetLiveStreamPlayerInfo Get live stream video public
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
	 */

	GetLiveStreamPlayerInfo(id string) (*GetLiveStreamVideoPublicResponse, error)

	/*
	 * GetLiveStreamPlayerInfo Get live stream video public
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
	 */

	GetLiveStreamPlayerInfoWithContext(ctx context.Context, id string) (*GetLiveStreamVideoPublicResponse, error)

	/*
	 * GetLiveStreamVideo Get live stream video
	 * @param id Live stream video ID
	 * @return LiveStreamApiGetLiveStreamVideoRequest
	 */

	GetLiveStreamVideo(id string) (*GetLiveStreamVideoResponse, error)

	/*
	 * GetLiveStreamVideo Get live stream video
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream video ID
	 * @return LiveStreamApiGetLiveStreamVideoRequest
	 */

	GetLiveStreamVideoWithContext(ctx context.Context, id string) (*GetLiveStreamVideoResponse, error)

	/*
	 * GetLiveStreamVideos Get live stream videos
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamVideosRequest
	 */

	GetLiveStreamVideos(id string, data GetLiveStreamVideosRequest) (*GetLiveStreamVideosResponse, error)

	/*
	 * GetLiveStreamVideos Get live stream videos
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetLiveStreamVideosRequest
	 */

	GetLiveStreamVideosWithContext(ctx context.Context, id string, data GetLiveStreamVideosRequest) (*GetLiveStreamVideosResponse, error)

	/*
	 * GetStreaming Get live stream video streaming
	 * @param id Live stream key ID
	 * @param streamId Stream ID
	 * @return LiveStreamApiGetStreamingRequest
	 */

	GetStreaming(id string, streamId string) (*GetStreamingResponse, error)

	/*
	 * GetStreaming Get live stream video streaming
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @param streamId Stream ID
	 * @return LiveStreamApiGetStreamingRequest
	 */

	GetStreamingWithContext(ctx context.Context, id string, streamId string) (*GetStreamingResponse, error)

	/*
	 * GetStreamings Get live stream video streamings
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetStreamingsRequest
	 */

	GetStreamings(id string) (*GetStreamingsResponse, error)

	/*
	 * GetStreamings Get live stream video streamings
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiGetStreamingsRequest
	 */

	GetStreamingsWithContext(ctx context.Context, id string) (*GetStreamingsResponse, error)

	/*
	 * UpdateLiveStreamKey Update live stream key
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamKeyRequest
	 */

	UpdateLiveStreamKey(id string, input UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error)

	/*
	 * UpdateLiveStreamKey Update live stream key
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamKeyRequest
	 */

	UpdateLiveStreamKeyWithContext(ctx context.Context, id string, input UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error)

	/*
	 * UpdateLiveStreamVideo Update live stream video
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamVideoRequest
	 */

	UpdateLiveStreamVideo(id string, data UpdateLiveStreamVideoRequest) (*ResponseSuccess, error)

	/*
	 * UpdateLiveStreamVideo Update live stream video
	 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	 * @param id Live stream key ID
	 * @return LiveStreamApiUpdateLiveStreamVideoRequest
	 */

	UpdateLiveStreamVideoWithContext(ctx context.Context, id string, data UpdateLiveStreamVideoRequest) (*ResponseSuccess, error)
}

// LiveStreamService communicating with the LiveStream
// endpoints of the w3stream API
type LiveStreamService struct {
	client *Client
}

/*
 * CreateLiveStreamKey Create live stream key
 * Create live stream key

 * @return LiveStreamApiCreateLiveStreamKeyRequest
 */

func (s *LiveStreamService) CreateLiveStreamKey(input CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error) {

	return s.CreateLiveStreamKeyWithContext(context.Background(), input)

}

/*
 * CreateLiveStreamKey Create live stream key
 * Create live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return LiveStreamApiCreateLiveStreamKeyRequest
 */

func (s *LiveStreamService) CreateLiveStreamKeyWithContext(ctx context.Context, input CreateLiveStreamKeyRequest) (*CreateLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = input

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(CreateLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * CreateStreaming Create a new live stream video
 * Creates a new live stream video with the provided details

 * @param id Live stream key ID
 * @return LiveStreamApiCreateStreamingRequest
 */

func (s *LiveStreamService) CreateStreaming(id string, input CreateStreamingRequest) (*CreateStreamingResponse, error) {

	return s.CreateStreamingWithContext(context.Background(), id, input)

}

/*
 * CreateStreaming Create a new live stream video
 * Creates a new live stream video with the provided details
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiCreateStreamingRequest
 */

func (s *LiveStreamService) CreateStreamingWithContext(ctx context.Context, id string, input CreateStreamingRequest) (*CreateStreamingResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = input

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(CreateStreamingResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteLiveStreamKey Delete live stream key
 * Delete a live stream key by ID

 * @param id Live stream key ID
 * @return LiveStreamApiDeleteLiveStreamKeyRequest
 */

func (s *LiveStreamService) DeleteLiveStreamKey(id string) (*ResponseSuccess, error) {

	return s.DeleteLiveStreamKeyWithContext(context.Background(), id)

}

/*
 * DeleteLiveStreamKey Delete live stream key
 * Delete a live stream key by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiDeleteLiveStreamKeyRequest
 */

func (s *LiveStreamService) DeleteLiveStreamKeyWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * DeleteLiveStreamVideo Delete live stream video
 * Delete a live stream video by ID

 * @param id Live stream video ID
 * @return LiveStreamApiDeleteLiveStreamVideoRequest
 */

func (s *LiveStreamService) DeleteLiveStreamVideo(id string) (*ResponseSuccess, error) {

	return s.DeleteLiveStreamVideoWithContext(context.Background(), id)

}

/*
 * DeleteLiveStreamVideo Delete live stream video
 * Delete a live stream video by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream video ID
 * @return LiveStreamApiDeleteLiveStreamVideoRequest
 */

func (s *LiveStreamService) DeleteLiveStreamVideoWithContext(ctx context.Context, id string) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/videos"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodDelete, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamKey Get live stream key
 * Get live stream key

 * @param id ID
 * @return LiveStreamApiGetLiveStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamKey(id string) (*GetLiveStreamKeyResponse, error) {

	return s.GetLiveStreamKeyWithContext(context.Background(), id)

}

/*
 * GetLiveStreamKey Get live stream key
 * Get live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id ID
 * @return LiveStreamApiGetLiveStreamKeyRequest
 */

func (s *LiveStreamService) GetLiveStreamKeyWithContext(ctx context.Context, id string) (*GetLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamKeys Get live stream key list
 * Get live stream key list

 * @return LiveStreamApiGetLiveStreamKeysRequest
 */

func (s *LiveStreamService) GetLiveStreamKeys(r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error) {

	return s.GetLiveStreamKeysWithContext(context.Background(), r)

}

/*
 * GetLiveStreamKeys Get live stream key list
 * Get live stream key list
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return LiveStreamApiGetLiveStreamKeysRequest
 */

func (s *LiveStreamService) GetLiveStreamKeysWithContext(ctx context.Context, r LiveStreamApiGetLiveStreamKeysRequest) (*GetLiveStreamKeysListResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	if r.search != nil {
		localVarQueryParams.Add("search", parameterToString(*r.search, ""))
	}
	if r.sortBy != nil {
		localVarQueryParams.Add("sort_by", parameterToString(*r.sortBy, ""))
	}
	if r.orderBy != nil {
		localVarQueryParams.Add("order_by", parameterToString(*r.orderBy, ""))
	}
	if r.offset != nil {
		localVarQueryParams.Add("offset", parameterToString(*r.offset, ""))
	}
	if r.limit != nil {
		localVarQueryParams.Add("limit", parameterToString(*r.limit, ""))
	}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamKeysListResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamPlayerInfo Get live stream video public
 * Get live stream video public for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
 */

func (s *LiveStreamService) GetLiveStreamPlayerInfo(id string) (*GetLiveStreamVideoPublicResponse, error) {

	return s.GetLiveStreamPlayerInfoWithContext(context.Background(), id)

}

/*
 * GetLiveStreamPlayerInfo Get live stream video public
 * Get live stream video public for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamPlayerInfoRequest
 */

func (s *LiveStreamService) GetLiveStreamPlayerInfoWithContext(ctx context.Context, id string) (*GetLiveStreamVideoPublicResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/player/{id}/videos"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamVideoPublicResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamVideo Get live stream video
 * Get a specific live stream video by ID

 * @param id Live stream video ID
 * @return LiveStreamApiGetLiveStreamVideoRequest
 */

func (s *LiveStreamService) GetLiveStreamVideo(id string) (*GetLiveStreamVideoResponse, error) {

	return s.GetLiveStreamVideoWithContext(context.Background(), id)

}

/*
 * GetLiveStreamVideo Get live stream video
 * Get a specific live stream video by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream video ID
 * @return LiveStreamApiGetLiveStreamVideoRequest
 */

func (s *LiveStreamService) GetLiveStreamVideoWithContext(ctx context.Context, id string) (*GetLiveStreamVideoResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/videos"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamVideoResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetLiveStreamVideos Get live stream videos
 * Get live stream videos for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamVideosRequest
 */

func (s *LiveStreamService) GetLiveStreamVideos(id string, data GetLiveStreamVideosRequest) (*GetLiveStreamVideosResponse, error) {

	return s.GetLiveStreamVideosWithContext(context.Background(), id, data)

}

/*
 * GetLiveStreamVideos Get live stream videos
 * Get live stream videos for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetLiveStreamVideosRequest
 */

func (s *LiveStreamService) GetLiveStreamVideosWithContext(ctx context.Context, id string, data GetLiveStreamVideosRequest) (*GetLiveStreamVideosResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/videos"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = data

	req, err := s.client.prepareRequest(ctx, http.MethodPost, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetLiveStreamVideosResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetStreaming Get live stream video streaming
 * Get live stream video streaming for a specific live stream key

 * @param id Live stream key ID
 * @param streamId Stream ID
 * @return LiveStreamApiGetStreamingRequest
 */

func (s *LiveStreamService) GetStreaming(id string, streamId string) (*GetStreamingResponse, error) {

	return s.GetStreamingWithContext(context.Background(), id, streamId)

}

/*
 * GetStreaming Get live stream video streaming
 * Get live stream video streaming for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @param streamId Stream ID
 * @return LiveStreamApiGetStreamingRequest
 */

func (s *LiveStreamService) GetStreamingWithContext(ctx context.Context, id string, streamId string) (*GetStreamingResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings/{stream_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)
	localVarPath = strings.Replace(localVarPath, "{"+"stream_id"+"}", url.PathEscape(parameterToString(streamId, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetStreamingResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * GetStreamings Get live stream video streamings
 * Get live stream video streamings for a specific live stream key

 * @param id Live stream key ID
 * @return LiveStreamApiGetStreamingsRequest
 */

func (s *LiveStreamService) GetStreamings(id string) (*GetStreamingsResponse, error) {

	return s.GetStreamingsWithContext(context.Background(), id)

}

/*
 * GetStreamings Get live stream video streamings
 * Get live stream video streamings for a specific live stream key
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiGetStreamingsRequest
 */

func (s *LiveStreamService) GetStreamingsWithContext(ctx context.Context, id string) (*GetStreamingsResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	req, err := s.client.prepareRequest(ctx, http.MethodGet, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(GetStreamingsResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UpdateLiveStreamKey Update live stream key
 * Update a live stream key by ID

 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamKeyRequest
 */

func (s *LiveStreamService) UpdateLiveStreamKey(id string, input UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error) {

	return s.UpdateLiveStreamKeyWithContext(context.Background(), id, input)

}

/*
 * UpdateLiveStreamKey Update live stream key
 * Update a live stream key by ID
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamKeyRequest
 */

func (s *LiveStreamService) UpdateLiveStreamKeyWithContext(ctx context.Context, id string, input UpdateLiveStreamKeyRequest) (*UpdateLiveStreamKeyResponse, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = input

	req, err := s.client.prepareRequest(ctx, http.MethodPut, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(UpdateLiveStreamKeyResponse)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}

/*
 * UpdateLiveStreamVideo Update live stream video
 * Update live stream video. You can only update while live streaming.

 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamVideoRequest
 */

func (s *LiveStreamService) UpdateLiveStreamVideo(id string, data UpdateLiveStreamVideoRequest) (*ResponseSuccess, error) {

	return s.UpdateLiveStreamVideoWithContext(context.Background(), id, data)

}

/*
 * UpdateLiveStreamVideo Update live stream video
 * Update live stream video. You can only update while live streaming.
 * @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param id Live stream key ID
 * @return LiveStreamApiUpdateLiveStreamVideoRequest
 */

func (s *LiveStreamService) UpdateLiveStreamVideoWithContext(ctx context.Context, id string, data UpdateLiveStreamVideoRequest) (*ResponseSuccess, error) {
	var localVarPostBody interface{}

	localVarPath := "/live_streams/{id}/streamings"
	localVarPath = strings.Replace(localVarPath, "{"+"id"+"}", url.PathEscape(parameterToString(id, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}

	// body params
	localVarPostBody = data

	req, err := s.client.prepareRequest(ctx, http.MethodPut, localVarPath, localVarPostBody, localVarHeaderParams, localVarQueryParams)
	if err != nil {
		return nil, err
	}

	res := new(ResponseSuccess)
	_, err = s.client.do(req, res)

	if err != nil {
		return nil, err
	}

	return res, nil

}
