/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateVideoChapterData struct for CreateVideoChapterData
type CreateVideoChapterData struct {
	VideoChapter *VideoChapter `json:"video_chapter,omitempty"`
}

// NewCreateVideoChapterData instantiates a new CreateVideoChapterData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVideoChapterData() *CreateVideoChapterData {
	this := CreateVideoChapterData{}
	return &this
}

// NewCreateVideoChapterDataWithDefaults instantiates a new CreateVideoChapterData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVideoChapterDataWithDefaults() *CreateVideoChapterData {
	this := CreateVideoChapterData{}
	return &this
}

// GetVideoChapter returns the VideoChapter field value if set, zero value otherwise.
func (o *CreateVideoChapterData) GetVideoChapter() VideoChapter {
	if o == nil || o.VideoChapter == nil {
		var ret VideoChapter
		return ret
	}
	return *o.VideoChapter
}

// GetVideoChapterOk returns a tuple with the VideoChapter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVideoChapterData) GetVideoChapterOk() (*VideoChapter, bool) {
	if o == nil || o.VideoChapter == nil {
		return nil, false
	}
	return o.VideoChapter, true
}

// HasVideoChapter returns a boolean if a field has been set.
func (o *CreateVideoChapterData) HasVideoChapter() bool {
	if o != nil && o.VideoChapter != nil {
		return true
	}

	return false
}

// SetVideoChapter gets a reference to the given VideoChapter and assigns it to the VideoChapter field.
func (o *CreateVideoChapterData) SetVideoChapter(v VideoChapter) {
	o.VideoChapter = &v
}

type NullableCreateVideoChapterData struct {
	value *CreateVideoChapterData
	isSet bool
}

func (v NullableCreateVideoChapterData) Get() *CreateVideoChapterData {
	return v.value
}

func (v *NullableCreateVideoChapterData) Set(val *CreateVideoChapterData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVideoChapterData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVideoChapterData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVideoChapterData(val *CreateVideoChapterData) *NullableCreateVideoChapterData {
	return &NullableCreateVideoChapterData{value: val, isSet: true}
}
