/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// Theme struct for Theme
type Theme struct {
	ControlBarBackgroundColor *string `json:"control_bar_background_color,omitempty"`
	ControlBarHeight          *string `json:"control_bar_height,omitempty"`
	MainColor                 *string `json:"main_color,omitempty"`
	MenuBackgroundColor       *string `json:"menu_background_color,omitempty"`
	MenuItemBackgroundHover   *string `json:"menu_item_background_hover,omitempty"`
	ProgressBarCircleSize     *string `json:"progress_bar_circle_size,omitempty"`
	ProgressBarHeight         *string `json:"progress_bar_height,omitempty"`
	TextColor                 *string `json:"text_color,omitempty"`
	TextTrackBackground       *string `json:"text_track_background,omitempty"`
	TextTrackColor            *string `json:"text_track_color,omitempty"`
}

// NewTheme instantiates a new Theme object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTheme() *Theme {
	this := Theme{}
	return &this
}

// NewThemeWithDefaults instantiates a new Theme object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThemeWithDefaults() *Theme {
	this := Theme{}
	return &this
}

// GetControlBarBackgroundColor returns the ControlBarBackgroundColor field value if set, zero value otherwise.
func (o *Theme) GetControlBarBackgroundColor() string {
	if o == nil || o.ControlBarBackgroundColor == nil {
		var ret string
		return ret
	}
	return *o.ControlBarBackgroundColor
}

// GetControlBarBackgroundColorOk returns a tuple with the ControlBarBackgroundColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetControlBarBackgroundColorOk() (*string, bool) {
	if o == nil || o.ControlBarBackgroundColor == nil {
		return nil, false
	}
	return o.ControlBarBackgroundColor, true
}

// HasControlBarBackgroundColor returns a boolean if a field has been set.
func (o *Theme) HasControlBarBackgroundColor() bool {
	if o != nil && o.ControlBarBackgroundColor != nil {
		return true
	}

	return false
}

// SetControlBarBackgroundColor gets a reference to the given string and assigns it to the ControlBarBackgroundColor field.
func (o *Theme) SetControlBarBackgroundColor(v string) {
	o.ControlBarBackgroundColor = &v
}

// GetControlBarHeight returns the ControlBarHeight field value if set, zero value otherwise.
func (o *Theme) GetControlBarHeight() string {
	if o == nil || o.ControlBarHeight == nil {
		var ret string
		return ret
	}
	return *o.ControlBarHeight
}

// GetControlBarHeightOk returns a tuple with the ControlBarHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetControlBarHeightOk() (*string, bool) {
	if o == nil || o.ControlBarHeight == nil {
		return nil, false
	}
	return o.ControlBarHeight, true
}

// HasControlBarHeight returns a boolean if a field has been set.
func (o *Theme) HasControlBarHeight() bool {
	if o != nil && o.ControlBarHeight != nil {
		return true
	}

	return false
}

// SetControlBarHeight gets a reference to the given string and assigns it to the ControlBarHeight field.
func (o *Theme) SetControlBarHeight(v string) {
	o.ControlBarHeight = &v
}

// GetMainColor returns the MainColor field value if set, zero value otherwise.
func (o *Theme) GetMainColor() string {
	if o == nil || o.MainColor == nil {
		var ret string
		return ret
	}
	return *o.MainColor
}

// GetMainColorOk returns a tuple with the MainColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetMainColorOk() (*string, bool) {
	if o == nil || o.MainColor == nil {
		return nil, false
	}
	return o.MainColor, true
}

// HasMainColor returns a boolean if a field has been set.
func (o *Theme) HasMainColor() bool {
	if o != nil && o.MainColor != nil {
		return true
	}

	return false
}

// SetMainColor gets a reference to the given string and assigns it to the MainColor field.
func (o *Theme) SetMainColor(v string) {
	o.MainColor = &v
}

// GetMenuBackgroundColor returns the MenuBackgroundColor field value if set, zero value otherwise.
func (o *Theme) GetMenuBackgroundColor() string {
	if o == nil || o.MenuBackgroundColor == nil {
		var ret string
		return ret
	}
	return *o.MenuBackgroundColor
}

// GetMenuBackgroundColorOk returns a tuple with the MenuBackgroundColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetMenuBackgroundColorOk() (*string, bool) {
	if o == nil || o.MenuBackgroundColor == nil {
		return nil, false
	}
	return o.MenuBackgroundColor, true
}

// HasMenuBackgroundColor returns a boolean if a field has been set.
func (o *Theme) HasMenuBackgroundColor() bool {
	if o != nil && o.MenuBackgroundColor != nil {
		return true
	}

	return false
}

// SetMenuBackgroundColor gets a reference to the given string and assigns it to the MenuBackgroundColor field.
func (o *Theme) SetMenuBackgroundColor(v string) {
	o.MenuBackgroundColor = &v
}

// GetMenuItemBackgroundHover returns the MenuItemBackgroundHover field value if set, zero value otherwise.
func (o *Theme) GetMenuItemBackgroundHover() string {
	if o == nil || o.MenuItemBackgroundHover == nil {
		var ret string
		return ret
	}
	return *o.MenuItemBackgroundHover
}

// GetMenuItemBackgroundHoverOk returns a tuple with the MenuItemBackgroundHover field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetMenuItemBackgroundHoverOk() (*string, bool) {
	if o == nil || o.MenuItemBackgroundHover == nil {
		return nil, false
	}
	return o.MenuItemBackgroundHover, true
}

// HasMenuItemBackgroundHover returns a boolean if a field has been set.
func (o *Theme) HasMenuItemBackgroundHover() bool {
	if o != nil && o.MenuItemBackgroundHover != nil {
		return true
	}

	return false
}

// SetMenuItemBackgroundHover gets a reference to the given string and assigns it to the MenuItemBackgroundHover field.
func (o *Theme) SetMenuItemBackgroundHover(v string) {
	o.MenuItemBackgroundHover = &v
}

// GetProgressBarCircleSize returns the ProgressBarCircleSize field value if set, zero value otherwise.
func (o *Theme) GetProgressBarCircleSize() string {
	if o == nil || o.ProgressBarCircleSize == nil {
		var ret string
		return ret
	}
	return *o.ProgressBarCircleSize
}

// GetProgressBarCircleSizeOk returns a tuple with the ProgressBarCircleSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetProgressBarCircleSizeOk() (*string, bool) {
	if o == nil || o.ProgressBarCircleSize == nil {
		return nil, false
	}
	return o.ProgressBarCircleSize, true
}

// HasProgressBarCircleSize returns a boolean if a field has been set.
func (o *Theme) HasProgressBarCircleSize() bool {
	if o != nil && o.ProgressBarCircleSize != nil {
		return true
	}

	return false
}

// SetProgressBarCircleSize gets a reference to the given string and assigns it to the ProgressBarCircleSize field.
func (o *Theme) SetProgressBarCircleSize(v string) {
	o.ProgressBarCircleSize = &v
}

// GetProgressBarHeight returns the ProgressBarHeight field value if set, zero value otherwise.
func (o *Theme) GetProgressBarHeight() string {
	if o == nil || o.ProgressBarHeight == nil {
		var ret string
		return ret
	}
	return *o.ProgressBarHeight
}

// GetProgressBarHeightOk returns a tuple with the ProgressBarHeight field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetProgressBarHeightOk() (*string, bool) {
	if o == nil || o.ProgressBarHeight == nil {
		return nil, false
	}
	return o.ProgressBarHeight, true
}

// HasProgressBarHeight returns a boolean if a field has been set.
func (o *Theme) HasProgressBarHeight() bool {
	if o != nil && o.ProgressBarHeight != nil {
		return true
	}

	return false
}

// SetProgressBarHeight gets a reference to the given string and assigns it to the ProgressBarHeight field.
func (o *Theme) SetProgressBarHeight(v string) {
	o.ProgressBarHeight = &v
}

// GetTextColor returns the TextColor field value if set, zero value otherwise.
func (o *Theme) GetTextColor() string {
	if o == nil || o.TextColor == nil {
		var ret string
		return ret
	}
	return *o.TextColor
}

// GetTextColorOk returns a tuple with the TextColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetTextColorOk() (*string, bool) {
	if o == nil || o.TextColor == nil {
		return nil, false
	}
	return o.TextColor, true
}

// HasTextColor returns a boolean if a field has been set.
func (o *Theme) HasTextColor() bool {
	if o != nil && o.TextColor != nil {
		return true
	}

	return false
}

// SetTextColor gets a reference to the given string and assigns it to the TextColor field.
func (o *Theme) SetTextColor(v string) {
	o.TextColor = &v
}

// GetTextTrackBackground returns the TextTrackBackground field value if set, zero value otherwise.
func (o *Theme) GetTextTrackBackground() string {
	if o == nil || o.TextTrackBackground == nil {
		var ret string
		return ret
	}
	return *o.TextTrackBackground
}

// GetTextTrackBackgroundOk returns a tuple with the TextTrackBackground field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetTextTrackBackgroundOk() (*string, bool) {
	if o == nil || o.TextTrackBackground == nil {
		return nil, false
	}
	return o.TextTrackBackground, true
}

// HasTextTrackBackground returns a boolean if a field has been set.
func (o *Theme) HasTextTrackBackground() bool {
	if o != nil && o.TextTrackBackground != nil {
		return true
	}

	return false
}

// SetTextTrackBackground gets a reference to the given string and assigns it to the TextTrackBackground field.
func (o *Theme) SetTextTrackBackground(v string) {
	o.TextTrackBackground = &v
}

// GetTextTrackColor returns the TextTrackColor field value if set, zero value otherwise.
func (o *Theme) GetTextTrackColor() string {
	if o == nil || o.TextTrackColor == nil {
		var ret string
		return ret
	}
	return *o.TextTrackColor
}

// GetTextTrackColorOk returns a tuple with the TextTrackColor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Theme) GetTextTrackColorOk() (*string, bool) {
	if o == nil || o.TextTrackColor == nil {
		return nil, false
	}
	return o.TextTrackColor, true
}

// HasTextTrackColor returns a boolean if a field has been set.
func (o *Theme) HasTextTrackColor() bool {
	if o != nil && o.TextTrackColor != nil {
		return true
	}

	return false
}

// SetTextTrackColor gets a reference to the given string and assigns it to the TextTrackColor field.
func (o *Theme) SetTextTrackColor(v string) {
	o.TextTrackColor = &v
}

type NullableTheme struct {
	value *Theme
	isSet bool
}

func (v NullableTheme) Get() *Theme {
	return v.value
}

func (v *NullableTheme) Set(val *Theme) {
	v.value = val
	v.isSet = true
}

func (v NullableTheme) IsSet() bool {
	return v.isSet
}

func (v *NullableTheme) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTheme(val *Theme) *NullableTheme {
	return &NullableTheme{value: val, isSet: true}
}
