/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetPlaylistListRequest struct for GetPlaylistListRequest
type GetPlaylistListRequest struct {
	Limit    *int32      `json:"limit,omitempty"`
	Metadata *[]Metadata `json:"metadata,omitempty"`
	Offset   *int32      `json:"offset,omitempty"`
	OrderBy  *string     `json:"order_by,omitempty"`
	Search   *string     `json:"search,omitempty"`
	SortBy   *string     `json:"sort_by,omitempty"`
	Tags     *[]string   `json:"tags,omitempty"`
}

// NewGetPlaylistListRequest instantiates a new GetPlaylistListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlaylistListRequest() *GetPlaylistListRequest {
	this := GetPlaylistListRequest{}
	return &this
}

// NewGetPlaylistListRequestWithDefaults instantiates a new GetPlaylistListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlaylistListRequestWithDefaults() *GetPlaylistListRequest {
	this := GetPlaylistListRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetPlaylistListRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *GetPlaylistListRequest) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetPlaylistListRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *GetPlaylistListRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetPlaylistListRequest) SetSearch(v string) {
	o.Search = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *GetPlaylistListRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetPlaylistListRequest) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListRequest) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetPlaylistListRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetPlaylistListRequest) SetTags(v []string) {
	o.Tags = &v
}

type NullableGetPlaylistListRequest struct {
	value *GetPlaylistListRequest
	isSet bool
}

func (v NullableGetPlaylistListRequest) Get() *GetPlaylistListRequest {
	return v.value
}

func (v *NullableGetPlaylistListRequest) Set(val *GetPlaylistListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlaylistListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlaylistListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlaylistListRequest(val *GetPlaylistListRequest) *NullableGetPlaylistListRequest {
	return &NullableGetPlaylistListRequest{value: val, isSet: true}
}
