/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateStreamingResponse struct for CreateStreamingResponse
type CreateStreamingResponse struct {
	Data   *LiveStreamVideoData `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// NewCreateStreamingResponse instantiates a new CreateStreamingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateStreamingResponse() *CreateStreamingResponse {
	this := CreateStreamingResponse{}
	return &this
}

// NewCreateStreamingResponseWithDefaults instantiates a new CreateStreamingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateStreamingResponseWithDefaults() *CreateStreamingResponse {
	this := CreateStreamingResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateStreamingResponse) GetData() LiveStreamVideoData {
	if o == nil || o.Data == nil {
		var ret LiveStreamVideoData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStreamingResponse) GetDataOk() (*LiveStreamVideoData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateStreamingResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given LiveStreamVideoData and assigns it to the Data field.
func (o *CreateStreamingResponse) SetData(v LiveStreamVideoData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateStreamingResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateStreamingResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateStreamingResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateStreamingResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableCreateStreamingResponse struct {
	value *CreateStreamingResponse
	isSet bool
}

func (v NullableCreateStreamingResponse) Get() *CreateStreamingResponse {
	return v.value
}

func (v *NullableCreateStreamingResponse) Set(val *CreateStreamingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateStreamingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateStreamingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateStreamingResponse(val *CreateStreamingResponse) *NullableCreateStreamingResponse {
	return &NullableCreateStreamingResponse{value: val, isSet: true}
}
