/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// AddVideoToPlaylistRequest struct for AddVideoToPlaylistRequest
type AddVideoToPlaylistRequest struct {
	VideoId *string `json:"video_id,omitempty"`
}

// NewAddVideoToPlaylistRequest instantiates a new AddVideoToPlaylistRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddVideoToPlaylistRequest() *AddVideoToPlaylistRequest {
	this := AddVideoToPlaylistRequest{}
	return &this
}

// NewAddVideoToPlaylistRequestWithDefaults instantiates a new AddVideoToPlaylistRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddVideoToPlaylistRequestWithDefaults() *AddVideoToPlaylistRequest {
	this := AddVideoToPlaylistRequest{}
	return &this
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *AddVideoToPlaylistRequest) GetVideoId() string {
	if o == nil || o.VideoId == nil {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AddVideoToPlaylistRequest) GetVideoIdOk() (*string, bool) {
	if o == nil || o.VideoId == nil {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *AddVideoToPlaylistRequest) HasVideoId() bool {
	if o != nil && o.VideoId != nil {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *AddVideoToPlaylistRequest) SetVideoId(v string) {
	o.VideoId = &v
}

type NullableAddVideoToPlaylistRequest struct {
	value *AddVideoToPlaylistRequest
	isSet bool
}

func (v NullableAddVideoToPlaylistRequest) Get() *AddVideoToPlaylistRequest {
	return v.value
}

func (v *NullableAddVideoToPlaylistRequest) Set(val *AddVideoToPlaylistRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddVideoToPlaylistRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddVideoToPlaylistRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddVideoToPlaylistRequest(val *AddVideoToPlaylistRequest) *NullableAddVideoToPlaylistRequest {
	return &NullableAddVideoToPlaylistRequest{value: val, isSet: true}
}
