/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// UpdateLiveStreamVideoRequest struct for UpdateLiveStreamVideoRequest
type UpdateLiveStreamVideoRequest struct {
	Save  *bool   `json:"save,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewUpdateLiveStreamVideoRequest instantiates a new UpdateLiveStreamVideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLiveStreamVideoRequest() *UpdateLiveStreamVideoRequest {
	this := UpdateLiveStreamVideoRequest{}
	return &this
}

// NewUpdateLiveStreamVideoRequestWithDefaults instantiates a new UpdateLiveStreamVideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLiveStreamVideoRequestWithDefaults() *UpdateLiveStreamVideoRequest {
	this := UpdateLiveStreamVideoRequest{}
	return &this
}

// GetSave returns the Save field value if set, zero value otherwise.
func (o *UpdateLiveStreamVideoRequest) GetSave() bool {
	if o == nil || o.Save == nil {
		var ret bool
		return ret
	}
	return *o.Save
}

// GetSaveOk returns a tuple with the Save field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLiveStreamVideoRequest) GetSaveOk() (*bool, bool) {
	if o == nil || o.Save == nil {
		return nil, false
	}
	return o.Save, true
}

// HasSave returns a boolean if a field has been set.
func (o *UpdateLiveStreamVideoRequest) HasSave() bool {
	if o != nil && o.Save != nil {
		return true
	}

	return false
}

// SetSave gets a reference to the given bool and assigns it to the Save field.
func (o *UpdateLiveStreamVideoRequest) SetSave(v bool) {
	o.Save = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *UpdateLiveStreamVideoRequest) GetTitle() string {
	if o == nil || o.Title == nil {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLiveStreamVideoRequest) GetTitleOk() (*string, bool) {
	if o == nil || o.Title == nil {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *UpdateLiveStreamVideoRequest) HasTitle() bool {
	if o != nil && o.Title != nil {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *UpdateLiveStreamVideoRequest) SetTitle(v string) {
	o.Title = &v
}

type NullableUpdateLiveStreamVideoRequest struct {
	value *UpdateLiveStreamVideoRequest
	isSet bool
}

func (v NullableUpdateLiveStreamVideoRequest) Get() *UpdateLiveStreamVideoRequest {
	return v.value
}

func (v *NullableUpdateLiveStreamVideoRequest) Set(val *UpdateLiveStreamVideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLiveStreamVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLiveStreamVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLiveStreamVideoRequest(val *UpdateLiveStreamVideoRequest) *NullableUpdateLiveStreamVideoRequest {
	return &NullableUpdateLiveStreamVideoRequest{value: val, isSet: true}
}
