/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetVideoDetailResponse struct for GetVideoDetailResponse
type GetVideoDetailResponse struct {
	Data   *VideoObject `json:"data,omitempty"`
	Status *string      `json:"status,omitempty"`
}

// NewGetVideoDetailResponse instantiates a new GetVideoDetailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideoDetailResponse() *GetVideoDetailResponse {
	this := GetVideoDetailResponse{}
	return &this
}

// NewGetVideoDetailResponseWithDefaults instantiates a new GetVideoDetailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideoDetailResponseWithDefaults() *GetVideoDetailResponse {
	this := GetVideoDetailResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetVideoDetailResponse) GetData() VideoObject {
	if o == nil || o.Data == nil {
		var ret VideoObject
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoDetailResponse) GetDataOk() (*VideoObject, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetVideoDetailResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given VideoObject and assigns it to the Data field.
func (o *GetVideoDetailResponse) SetData(v VideoObject) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVideoDetailResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoDetailResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVideoDetailResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVideoDetailResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetVideoDetailResponse struct {
	value *GetVideoDetailResponse
	isSet bool
}

func (v NullableGetVideoDetailResponse) Get() *GetVideoDetailResponse {
	return v.value
}

func (v *NullableGetVideoDetailResponse) Set(val *GetVideoDetailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideoDetailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideoDetailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideoDetailResponse(val *GetVideoDetailResponse) *NullableGetVideoDetailResponse {
	return &NullableGetVideoDetailResponse{value: val, isSet: true}
}
