/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetLiveStreamKeysListResponse struct for GetLiveStreamKeysListResponse
type GetLiveStreamKeysListResponse struct {
	Data   *GetLiveStreamKeysListData `json:"data,omitempty"`
	Status *string                    `json:"status,omitempty"`
}

// NewGetLiveStreamKeysListResponse instantiates a new GetLiveStreamKeysListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveStreamKeysListResponse() *GetLiveStreamKeysListResponse {
	this := GetLiveStreamKeysListResponse{}
	return &this
}

// NewGetLiveStreamKeysListResponseWithDefaults instantiates a new GetLiveStreamKeysListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveStreamKeysListResponseWithDefaults() *GetLiveStreamKeysListResponse {
	this := GetLiveStreamKeysListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLiveStreamKeysListResponse) GetData() GetLiveStreamKeysListData {
	if o == nil || o.Data == nil {
		var ret GetLiveStreamKeysListData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamKeysListResponse) GetDataOk() (*GetLiveStreamKeysListData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLiveStreamKeysListResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetLiveStreamKeysListData and assigns it to the Data field.
func (o *GetLiveStreamKeysListResponse) SetData(v GetLiveStreamKeysListData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLiveStreamKeysListResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamKeysListResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLiveStreamKeysListResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLiveStreamKeysListResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetLiveStreamKeysListResponse struct {
	value *GetLiveStreamKeysListResponse
	isSet bool
}

func (v NullableGetLiveStreamKeysListResponse) Get() *GetLiveStreamKeysListResponse {
	return v.value
}

func (v *NullableGetLiveStreamKeysListResponse) Set(val *GetLiveStreamKeysListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveStreamKeysListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveStreamKeysListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveStreamKeysListResponse(val *GetLiveStreamKeysListResponse) *NullableGetLiveStreamKeysListResponse {
	return &NullableGetLiveStreamKeysListResponse{value: val, isSet: true}
}
