/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetUserWebhookResponse struct for GetUserWebhookResponse
type GetUserWebhookResponse struct {
	Data   *GetUserWebhookData `json:"data,omitempty"`
	Status *string             `json:"status,omitempty"`
}

// NewGetUserWebhookResponse instantiates a new GetUserWebhookResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserWebhookResponse() *GetUserWebhookResponse {
	this := GetUserWebhookResponse{}
	return &this
}

// NewGetUserWebhookResponseWithDefaults instantiates a new GetUserWebhookResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserWebhookResponseWithDefaults() *GetUserWebhookResponse {
	this := GetUserWebhookResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetUserWebhookResponse) GetData() GetUserWebhookData {
	if o == nil || o.Data == nil {
		var ret GetUserWebhookData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserWebhookResponse) GetDataOk() (*GetUserWebhookData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetUserWebhookResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetUserWebhookData and assigns it to the Data field.
func (o *GetUserWebhookResponse) SetData(v GetUserWebhookData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetUserWebhookResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetUserWebhookResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetUserWebhookResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetUserWebhookResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetUserWebhookResponse struct {
	value *GetUserWebhookResponse
	isSet bool
}

func (v NullableGetUserWebhookResponse) Get() *GetUserWebhookResponse {
	return v.value
}

func (v *NullableGetUserWebhookResponse) Set(val *GetUserWebhookResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserWebhookResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserWebhookResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserWebhookResponse(val *GetUserWebhookResponse) *NullableGetUserWebhookResponse {
	return &NullableGetUserWebhookResponse{value: val, isSet: true}
}
