/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetAllWatermarkResponse struct for GetAllWatermarkResponse
type GetAllWatermarkResponse struct {
	Data   *GetAllWatermarkData `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// NewGetAllWatermarkResponse instantiates a new GetAllWatermarkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllWatermarkResponse() *GetAllWatermarkResponse {
	this := GetAllWatermarkResponse{}
	return &this
}

// NewGetAllWatermarkResponseWithDefaults instantiates a new GetAllWatermarkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllWatermarkResponseWithDefaults() *GetAllWatermarkResponse {
	this := GetAllWatermarkResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetAllWatermarkResponse) GetData() GetAllWatermarkData {
	if o == nil || o.Data == nil {
		var ret GetAllWatermarkData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllWatermarkResponse) GetDataOk() (*GetAllWatermarkData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetAllWatermarkResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetAllWatermarkData and assigns it to the Data field.
func (o *GetAllWatermarkResponse) SetData(v GetAllWatermarkData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetAllWatermarkResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllWatermarkResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetAllWatermarkResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetAllWatermarkResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetAllWatermarkResponse struct {
	value *GetAllWatermarkResponse
	isSet bool
}

func (v NullableGetAllWatermarkResponse) Get() *GetAllWatermarkResponse {
	return v.value
}

func (v *NullableGetAllWatermarkResponse) Set(val *GetAllWatermarkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllWatermarkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllWatermarkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllWatermarkResponse(val *GetAllWatermarkResponse) *NullableGetAllWatermarkResponse {
	return &NullableGetAllWatermarkResponse{value: val, isSet: true}
}
