/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetLiveStreamKeysListData struct for GetLiveStreamKeysListData
type GetLiveStreamKeysListData struct {
	LiveStreamKeys *[]GetLiveStreamKeyData `json:"live_stream_keys,omitempty"`
	Total          *int32                  `json:"total,omitempty"`
}

// NewGetLiveStreamKeysListData instantiates a new GetLiveStreamKeysListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveStreamKeysListData() *GetLiveStreamKeysListData {
	this := GetLiveStreamKeysListData{}
	return &this
}

// NewGetLiveStreamKeysListDataWithDefaults instantiates a new GetLiveStreamKeysListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveStreamKeysListDataWithDefaults() *GetLiveStreamKeysListData {
	this := GetLiveStreamKeysListData{}
	return &this
}

// GetLiveStreamKeys returns the LiveStreamKeys field value if set, zero value otherwise.
func (o *GetLiveStreamKeysListData) GetLiveStreamKeys() []GetLiveStreamKeyData {
	if o == nil || o.LiveStreamKeys == nil {
		var ret []GetLiveStreamKeyData
		return ret
	}
	return *o.LiveStreamKeys
}

// GetLiveStreamKeysOk returns a tuple with the LiveStreamKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamKeysListData) GetLiveStreamKeysOk() (*[]GetLiveStreamKeyData, bool) {
	if o == nil || o.LiveStreamKeys == nil {
		return nil, false
	}
	return o.LiveStreamKeys, true
}

// HasLiveStreamKeys returns a boolean if a field has been set.
func (o *GetLiveStreamKeysListData) HasLiveStreamKeys() bool {
	if o != nil && o.LiveStreamKeys != nil {
		return true
	}

	return false
}

// SetLiveStreamKeys gets a reference to the given []GetLiveStreamKeyData and assigns it to the LiveStreamKeys field.
func (o *GetLiveStreamKeysListData) SetLiveStreamKeys(v []GetLiveStreamKeyData) {
	o.LiveStreamKeys = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetLiveStreamKeysListData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamKeysListData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetLiveStreamKeysListData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetLiveStreamKeysListData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetLiveStreamKeysListData struct {
	value *GetLiveStreamKeysListData
	isSet bool
}

func (v NullableGetLiveStreamKeysListData) Get() *GetLiveStreamKeysListData {
	return v.value
}

func (v *NullableGetLiveStreamKeysListData) Set(val *GetLiveStreamKeysListData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveStreamKeysListData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveStreamKeysListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveStreamKeysListData(val *GetLiveStreamKeysListData) *NullableGetLiveStreamKeysListData {
	return &NullableGetLiveStreamKeysListData{value: val, isSet: true}
}
