/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetPlayerThemeByIdData struct for GetPlayerThemeByIdData
type GetPlayerThemeByIdData struct {
	PlayerTheme *PlayerTheme `json:"player_theme,omitempty"`
}

// NewGetPlayerThemeByIdData instantiates a new GetPlayerThemeByIdData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlayerThemeByIdData() *GetPlayerThemeByIdData {
	this := GetPlayerThemeByIdData{}
	return &this
}

// NewGetPlayerThemeByIdDataWithDefaults instantiates a new GetPlayerThemeByIdData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlayerThemeByIdDataWithDefaults() *GetPlayerThemeByIdData {
	this := GetPlayerThemeByIdData{}
	return &this
}

// GetPlayerTheme returns the PlayerTheme field value if set, zero value otherwise.
func (o *GetPlayerThemeByIdData) GetPlayerTheme() PlayerTheme {
	if o == nil || o.PlayerTheme == nil {
		var ret PlayerTheme
		return ret
	}
	return *o.PlayerTheme
}

// GetPlayerThemeOk returns a tuple with the PlayerTheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlayerThemeByIdData) GetPlayerThemeOk() (*PlayerTheme, bool) {
	if o == nil || o.PlayerTheme == nil {
		return nil, false
	}
	return o.PlayerTheme, true
}

// HasPlayerTheme returns a boolean if a field has been set.
func (o *GetPlayerThemeByIdData) HasPlayerTheme() bool {
	if o != nil && o.PlayerTheme != nil {
		return true
	}

	return false
}

// SetPlayerTheme gets a reference to the given PlayerTheme and assigns it to the PlayerTheme field.
func (o *GetPlayerThemeByIdData) SetPlayerTheme(v PlayerTheme) {
	o.PlayerTheme = &v
}

type NullableGetPlayerThemeByIdData struct {
	value *GetPlayerThemeByIdData
	isSet bool
}

func (v NullableGetPlayerThemeByIdData) Get() *GetPlayerThemeByIdData {
	return v.value
}

func (v *NullableGetPlayerThemeByIdData) Set(val *GetPlayerThemeByIdData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlayerThemeByIdData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlayerThemeByIdData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlayerThemeByIdData(val *GetPlayerThemeByIdData) *NullableGetPlayerThemeByIdData {
	return &NullableGetPlayerThemeByIdData{value: val, isSet: true}
}
