/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateWatermarkResponse struct for CreateWatermarkResponse
type CreateWatermarkResponse struct {
	Data   *CreateWatermarkData `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// NewCreateWatermarkResponse instantiates a new CreateWatermarkResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWatermarkResponse() *CreateWatermarkResponse {
	this := CreateWatermarkResponse{}
	return &this
}

// NewCreateWatermarkResponseWithDefaults instantiates a new CreateWatermarkResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWatermarkResponseWithDefaults() *CreateWatermarkResponse {
	this := CreateWatermarkResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateWatermarkResponse) GetData() CreateWatermarkData {
	if o == nil || o.Data == nil {
		var ret CreateWatermarkData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWatermarkResponse) GetDataOk() (*CreateWatermarkData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateWatermarkResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateWatermarkData and assigns it to the Data field.
func (o *CreateWatermarkResponse) SetData(v CreateWatermarkData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateWatermarkResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWatermarkResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateWatermarkResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateWatermarkResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableCreateWatermarkResponse struct {
	value *CreateWatermarkResponse
	isSet bool
}

func (v NullableCreateWatermarkResponse) Get() *CreateWatermarkResponse {
	return v.value
}

func (v *NullableCreateWatermarkResponse) Set(val *CreateWatermarkResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWatermarkResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWatermarkResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWatermarkResponse(val *CreateWatermarkResponse) *NullableCreateWatermarkResponse {
	return &NullableCreateWatermarkResponse{value: val, isSet: true}
}
