/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// LiveStreamAssets struct for LiveStreamAssets
type LiveStreamAssets struct {
	HlsUrl       *string `json:"hls_url,omitempty"`
	ThumbnailUrl *string `json:"thumbnail_url,omitempty"`
}

// NewLiveStreamAssets instantiates a new LiveStreamAssets object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveStreamAssets() *LiveStreamAssets {
	this := LiveStreamAssets{}
	return &this
}

// NewLiveStreamAssetsWithDefaults instantiates a new LiveStreamAssets object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveStreamAssetsWithDefaults() *LiveStreamAssets {
	this := LiveStreamAssets{}
	return &this
}

// GetHlsUrl returns the HlsUrl field value if set, zero value otherwise.
func (o *LiveStreamAssets) GetHlsUrl() string {
	if o == nil || o.HlsUrl == nil {
		var ret string
		return ret
	}
	return *o.HlsUrl
}

// GetHlsUrlOk returns a tuple with the HlsUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamAssets) GetHlsUrlOk() (*string, bool) {
	if o == nil || o.HlsUrl == nil {
		return nil, false
	}
	return o.HlsUrl, true
}

// HasHlsUrl returns a boolean if a field has been set.
func (o *LiveStreamAssets) HasHlsUrl() bool {
	if o != nil && o.HlsUrl != nil {
		return true
	}

	return false
}

// SetHlsUrl gets a reference to the given string and assigns it to the HlsUrl field.
func (o *LiveStreamAssets) SetHlsUrl(v string) {
	o.HlsUrl = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *LiveStreamAssets) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamAssets) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || o.ThumbnailUrl == nil {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *LiveStreamAssets) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl != nil {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *LiveStreamAssets) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

type NullableLiveStreamAssets struct {
	value *LiveStreamAssets
	isSet bool
}

func (v NullableLiveStreamAssets) Get() *LiveStreamAssets {
	return v.value
}

func (v *NullableLiveStreamAssets) Set(val *LiveStreamAssets) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveStreamAssets) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveStreamAssets) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveStreamAssets(val *LiveStreamAssets) *NullableLiveStreamAssets {
	return &NullableLiveStreamAssets{value: val, isSet: true}
}
