/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetAllWatermarkData struct for GetAllWatermarkData
type GetAllWatermarkData struct {
	Total      *int32       `json:"total,omitempty"`
	Watermarks *[]Watermark `json:"watermarks,omitempty"`
}

// NewGetAllWatermarkData instantiates a new GetAllWatermarkData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAllWatermarkData() *GetAllWatermarkData {
	this := GetAllWatermarkData{}
	return &this
}

// NewGetAllWatermarkDataWithDefaults instantiates a new GetAllWatermarkData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAllWatermarkDataWithDefaults() *GetAllWatermarkData {
	this := GetAllWatermarkData{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetAllWatermarkData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllWatermarkData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetAllWatermarkData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetAllWatermarkData) SetTotal(v int32) {
	o.Total = &v
}

// GetWatermarks returns the Watermarks field value if set, zero value otherwise.
func (o *GetAllWatermarkData) GetWatermarks() []Watermark {
	if o == nil || o.Watermarks == nil {
		var ret []Watermark
		return ret
	}
	return *o.Watermarks
}

// GetWatermarksOk returns a tuple with the Watermarks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetAllWatermarkData) GetWatermarksOk() (*[]Watermark, bool) {
	if o == nil || o.Watermarks == nil {
		return nil, false
	}
	return o.Watermarks, true
}

// HasWatermarks returns a boolean if a field has been set.
func (o *GetAllWatermarkData) HasWatermarks() bool {
	if o != nil && o.Watermarks != nil {
		return true
	}

	return false
}

// SetWatermarks gets a reference to the given []Watermark and assigns it to the Watermarks field.
func (o *GetAllWatermarkData) SetWatermarks(v []Watermark) {
	o.Watermarks = &v
}

type NullableGetAllWatermarkData struct {
	value *GetAllWatermarkData
	isSet bool
}

func (v NullableGetAllWatermarkData) Get() *GetAllWatermarkData {
	return v.value
}

func (v *NullableGetAllWatermarkData) Set(val *GetAllWatermarkData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAllWatermarkData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAllWatermarkData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAllWatermarkData(val *GetAllWatermarkData) *NullableGetAllWatermarkData {
	return &NullableGetAllWatermarkData{value: val, isSet: true}
}
