/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// LiveStreamVideosResponse struct for LiveStreamVideosResponse
type LiveStreamVideosResponse struct {
	Total  *int32                     `json:"total,omitempty"`
	Videos *[]LiveStreamVideoResponse `json:"videos,omitempty"`
}

// NewLiveStreamVideosResponse instantiates a new LiveStreamVideosResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLiveStreamVideosResponse() *LiveStreamVideosResponse {
	this := LiveStreamVideosResponse{}
	return &this
}

// NewLiveStreamVideosResponseWithDefaults instantiates a new LiveStreamVideosResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLiveStreamVideosResponseWithDefaults() *LiveStreamVideosResponse {
	this := LiveStreamVideosResponse{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *LiveStreamVideosResponse) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamVideosResponse) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *LiveStreamVideosResponse) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *LiveStreamVideosResponse) SetTotal(v int32) {
	o.Total = &v
}

// GetVideos returns the Videos field value if set, zero value otherwise.
func (o *LiveStreamVideosResponse) GetVideos() []LiveStreamVideoResponse {
	if o == nil || o.Videos == nil {
		var ret []LiveStreamVideoResponse
		return ret
	}
	return *o.Videos
}

// GetVideosOk returns a tuple with the Videos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LiveStreamVideosResponse) GetVideosOk() (*[]LiveStreamVideoResponse, bool) {
	if o == nil || o.Videos == nil {
		return nil, false
	}
	return o.Videos, true
}

// HasVideos returns a boolean if a field has been set.
func (o *LiveStreamVideosResponse) HasVideos() bool {
	if o != nil && o.Videos != nil {
		return true
	}

	return false
}

// SetVideos gets a reference to the given []LiveStreamVideoResponse and assigns it to the Videos field.
func (o *LiveStreamVideosResponse) SetVideos(v []LiveStreamVideoResponse) {
	o.Videos = &v
}

type NullableLiveStreamVideosResponse struct {
	value *LiveStreamVideosResponse
	isSet bool
}

func (v NullableLiveStreamVideosResponse) Get() *LiveStreamVideosResponse {
	return v.value
}

func (v *NullableLiveStreamVideosResponse) Set(val *LiveStreamVideosResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableLiveStreamVideosResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableLiveStreamVideosResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLiveStreamVideosResponse(val *LiveStreamVideosResponse) *NullableLiveStreamVideosResponse {
	return &NullableLiveStreamVideosResponse{value: val, isSet: true}
}
