/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetVideoListData struct for GetVideoListData
type GetVideoListData struct {
	Total  *int32   `json:"total,omitempty"`
	Videos *[]Video `json:"videos,omitempty"`
}

// NewGetVideoListData instantiates a new GetVideoListData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideoListData() *GetVideoListData {
	this := GetVideoListData{}
	return &this
}

// NewGetVideoListDataWithDefaults instantiates a new GetVideoListData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideoListDataWithDefaults() *GetVideoListData {
	this := GetVideoListData{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetVideoListData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetVideoListData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetVideoListData) SetTotal(v int32) {
	o.Total = &v
}

// GetVideos returns the Videos field value if set, zero value otherwise.
func (o *GetVideoListData) GetVideos() []Video {
	if o == nil || o.Videos == nil {
		var ret []Video
		return ret
	}
	return *o.Videos
}

// GetVideosOk returns a tuple with the Videos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListData) GetVideosOk() (*[]Video, bool) {
	if o == nil || o.Videos == nil {
		return nil, false
	}
	return o.Videos, true
}

// HasVideos returns a boolean if a field has been set.
func (o *GetVideoListData) HasVideos() bool {
	if o != nil && o.Videos != nil {
		return true
	}

	return false
}

// SetVideos gets a reference to the given []Video and assigns it to the Videos field.
func (o *GetVideoListData) SetVideos(v []Video) {
	o.Videos = &v
}

type NullableGetVideoListData struct {
	value *GetVideoListData
	isSet bool
}

func (v NullableGetVideoListData) Get() *GetVideoListData {
	return v.value
}

func (v *NullableGetVideoListData) Set(val *GetVideoListData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideoListData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideoListData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideoListData(val *GetVideoListData) *NullableGetVideoListData {
	return &NullableGetVideoListData{value: val, isSet: true}
}
