/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetVideoChaptersResponse struct for GetVideoChaptersResponse
type GetVideoChaptersResponse struct {
	Data   *GetVideoChaptersData `json:"data,omitempty"`
	Status *string               `json:"status,omitempty"`
}

// NewGetVideoChaptersResponse instantiates a new GetVideoChaptersResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideoChaptersResponse() *GetVideoChaptersResponse {
	this := GetVideoChaptersResponse{}
	return &this
}

// NewGetVideoChaptersResponseWithDefaults instantiates a new GetVideoChaptersResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideoChaptersResponseWithDefaults() *GetVideoChaptersResponse {
	this := GetVideoChaptersResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetVideoChaptersResponse) GetData() GetVideoChaptersData {
	if o == nil || o.Data == nil {
		var ret GetVideoChaptersData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoChaptersResponse) GetDataOk() (*GetVideoChaptersData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetVideoChaptersResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetVideoChaptersData and assigns it to the Data field.
func (o *GetVideoChaptersResponse) SetData(v GetVideoChaptersData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVideoChaptersResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoChaptersResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVideoChaptersResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVideoChaptersResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetVideoChaptersResponse struct {
	value *GetVideoChaptersResponse
	isSet bool
}

func (v NullableGetVideoChaptersResponse) Get() *GetVideoChaptersResponse {
	return v.value
}

func (v *NullableGetVideoChaptersResponse) Set(val *GetVideoChaptersResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideoChaptersResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideoChaptersResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideoChaptersResponse(val *GetVideoChaptersResponse) *NullableGetVideoChaptersResponse {
	return &NullableGetVideoChaptersResponse{value: val, isSet: true}
}
