/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateVideoChapterResponse struct for CreateVideoChapterResponse
type CreateVideoChapterResponse struct {
	Data   *CreateVideoChapterData `json:"data,omitempty"`
	Status *string                 `json:"status,omitempty"`
}

// NewCreateVideoChapterResponse instantiates a new CreateVideoChapterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVideoChapterResponse() *CreateVideoChapterResponse {
	this := CreateVideoChapterResponse{}
	return &this
}

// NewCreateVideoChapterResponseWithDefaults instantiates a new CreateVideoChapterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVideoChapterResponseWithDefaults() *CreateVideoChapterResponse {
	this := CreateVideoChapterResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateVideoChapterResponse) GetData() CreateVideoChapterData {
	if o == nil || o.Data == nil {
		var ret CreateVideoChapterData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVideoChapterResponse) GetDataOk() (*CreateVideoChapterData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateVideoChapterResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given CreateVideoChapterData and assigns it to the Data field.
func (o *CreateVideoChapterResponse) SetData(v CreateVideoChapterData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CreateVideoChapterResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateVideoChapterResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CreateVideoChapterResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CreateVideoChapterResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableCreateVideoChapterResponse struct {
	value *CreateVideoChapterResponse
	isSet bool
}

func (v NullableCreateVideoChapterResponse) Get() *CreateVideoChapterResponse {
	return v.value
}

func (v *NullableCreateVideoChapterResponse) Set(val *CreateVideoChapterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVideoChapterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVideoChapterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVideoChapterResponse(val *CreateVideoChapterResponse) *NullableCreateVideoChapterResponse {
	return &NullableCreateVideoChapterResponse{value: val, isSet: true}
}
