/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetPlaylistByIdResponse struct for GetPlaylistByIdResponse
type GetPlaylistByIdResponse struct {
	Data   *GetPlaylistByIdData `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// NewGetPlaylistByIdResponse instantiates a new GetPlaylistByIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlaylistByIdResponse() *GetPlaylistByIdResponse {
	this := GetPlaylistByIdResponse{}
	return &this
}

// NewGetPlaylistByIdResponseWithDefaults instantiates a new GetPlaylistByIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlaylistByIdResponseWithDefaults() *GetPlaylistByIdResponse {
	this := GetPlaylistByIdResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPlaylistByIdResponse) GetData() GetPlaylistByIdData {
	if o == nil || o.Data == nil {
		var ret GetPlaylistByIdData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistByIdResponse) GetDataOk() (*GetPlaylistByIdData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPlaylistByIdResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetPlaylistByIdData and assigns it to the Data field.
func (o *GetPlaylistByIdResponse) SetData(v GetPlaylistByIdData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetPlaylistByIdResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistByIdResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetPlaylistByIdResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetPlaylistByIdResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetPlaylistByIdResponse struct {
	value *GetPlaylistByIdResponse
	isSet bool
}

func (v NullableGetPlaylistByIdResponse) Get() *GetPlaylistByIdResponse {
	return v.value
}

func (v *NullableGetPlaylistByIdResponse) Set(val *GetPlaylistByIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlaylistByIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlaylistByIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlaylistByIdResponse(val *GetPlaylistByIdResponse) *NullableGetPlaylistByIdResponse {
	return &NullableGetPlaylistByIdResponse{value: val, isSet: true}
}
