/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// UpdateLiveStreamKeyResponse struct for UpdateLiveStreamKeyResponse
type UpdateLiveStreamKeyResponse struct {
	Data   *UpdateLiveStreamKeyData `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

// NewUpdateLiveStreamKeyResponse instantiates a new UpdateLiveStreamKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateLiveStreamKeyResponse() *UpdateLiveStreamKeyResponse {
	this := UpdateLiveStreamKeyResponse{}
	return &this
}

// NewUpdateLiveStreamKeyResponseWithDefaults instantiates a new UpdateLiveStreamKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateLiveStreamKeyResponseWithDefaults() *UpdateLiveStreamKeyResponse {
	this := UpdateLiveStreamKeyResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateLiveStreamKeyResponse) GetData() UpdateLiveStreamKeyData {
	if o == nil || o.Data == nil {
		var ret UpdateLiveStreamKeyData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLiveStreamKeyResponse) GetDataOk() (*UpdateLiveStreamKeyData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateLiveStreamKeyResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given UpdateLiveStreamKeyData and assigns it to the Data field.
func (o *UpdateLiveStreamKeyResponse) SetData(v UpdateLiveStreamKeyData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdateLiveStreamKeyResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateLiveStreamKeyResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdateLiveStreamKeyResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UpdateLiveStreamKeyResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableUpdateLiveStreamKeyResponse struct {
	value *UpdateLiveStreamKeyResponse
	isSet bool
}

func (v NullableUpdateLiveStreamKeyResponse) Get() *UpdateLiveStreamKeyResponse {
	return v.value
}

func (v *NullableUpdateLiveStreamKeyResponse) Set(val *UpdateLiveStreamKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateLiveStreamKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateLiveStreamKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateLiveStreamKeyResponse(val *UpdateLiveStreamKeyResponse) *NullableUpdateLiveStreamKeyResponse {
	return &NullableUpdateLiveStreamKeyResponse{value: val, isSet: true}
}
