/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// RemovePlayerThemesFromVideoRequest struct for RemovePlayerThemesFromVideoRequest
type RemovePlayerThemesFromVideoRequest struct {
	PlayerThemeId *string `json:"player_theme_id,omitempty"`
	VideoId       *string `json:"video_id,omitempty"`
}

// NewRemovePlayerThemesFromVideoRequest instantiates a new RemovePlayerThemesFromVideoRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRemovePlayerThemesFromVideoRequest() *RemovePlayerThemesFromVideoRequest {
	this := RemovePlayerThemesFromVideoRequest{}
	return &this
}

// NewRemovePlayerThemesFromVideoRequestWithDefaults instantiates a new RemovePlayerThemesFromVideoRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRemovePlayerThemesFromVideoRequestWithDefaults() *RemovePlayerThemesFromVideoRequest {
	this := RemovePlayerThemesFromVideoRequest{}
	return &this
}

// GetPlayerThemeId returns the PlayerThemeId field value if set, zero value otherwise.
func (o *RemovePlayerThemesFromVideoRequest) GetPlayerThemeId() string {
	if o == nil || o.PlayerThemeId == nil {
		var ret string
		return ret
	}
	return *o.PlayerThemeId
}

// GetPlayerThemeIdOk returns a tuple with the PlayerThemeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePlayerThemesFromVideoRequest) GetPlayerThemeIdOk() (*string, bool) {
	if o == nil || o.PlayerThemeId == nil {
		return nil, false
	}
	return o.PlayerThemeId, true
}

// HasPlayerThemeId returns a boolean if a field has been set.
func (o *RemovePlayerThemesFromVideoRequest) HasPlayerThemeId() bool {
	if o != nil && o.PlayerThemeId != nil {
		return true
	}

	return false
}

// SetPlayerThemeId gets a reference to the given string and assigns it to the PlayerThemeId field.
func (o *RemovePlayerThemesFromVideoRequest) SetPlayerThemeId(v string) {
	o.PlayerThemeId = &v
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *RemovePlayerThemesFromVideoRequest) GetVideoId() string {
	if o == nil || o.VideoId == nil {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RemovePlayerThemesFromVideoRequest) GetVideoIdOk() (*string, bool) {
	if o == nil || o.VideoId == nil {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *RemovePlayerThemesFromVideoRequest) HasVideoId() bool {
	if o != nil && o.VideoId != nil {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *RemovePlayerThemesFromVideoRequest) SetVideoId(v string) {
	o.VideoId = &v
}

type NullableRemovePlayerThemesFromVideoRequest struct {
	value *RemovePlayerThemesFromVideoRequest
	isSet bool
}

func (v NullableRemovePlayerThemesFromVideoRequest) Get() *RemovePlayerThemesFromVideoRequest {
	return v.value
}

func (v *NullableRemovePlayerThemesFromVideoRequest) Set(val *RemovePlayerThemesFromVideoRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRemovePlayerThemesFromVideoRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRemovePlayerThemesFromVideoRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRemovePlayerThemesFromVideoRequest(val *RemovePlayerThemesFromVideoRequest) *NullableRemovePlayerThemesFromVideoRequest {
	return &NullableRemovePlayerThemesFromVideoRequest{value: val, isSet: true}
}
