/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// VideoChapter struct for VideoChapter
type VideoChapter struct {
	Language *string `json:"language,omitempty"`
	Url      *string `json:"url,omitempty"`
}

// NewVideoChapter instantiates a new VideoChapter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVideoChapter() *VideoChapter {
	this := VideoChapter{}
	return &this
}

// NewVideoChapterWithDefaults instantiates a new VideoChapter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVideoChapterWithDefaults() *VideoChapter {
	this := VideoChapter{}
	return &this
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *VideoChapter) GetLanguage() string {
	if o == nil || o.Language == nil {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoChapter) GetLanguageOk() (*string, bool) {
	if o == nil || o.Language == nil {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *VideoChapter) HasLanguage() bool {
	if o != nil && o.Language != nil {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *VideoChapter) SetLanguage(v string) {
	o.Language = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *VideoChapter) GetUrl() string {
	if o == nil || o.Url == nil {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VideoChapter) GetUrlOk() (*string, bool) {
	if o == nil || o.Url == nil {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *VideoChapter) HasUrl() bool {
	if o != nil && o.Url != nil {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *VideoChapter) SetUrl(v string) {
	o.Url = &v
}

type NullableVideoChapter struct {
	value *VideoChapter
	isSet bool
}

func (v NullableVideoChapter) Get() *VideoChapter {
	return v.value
}

func (v *NullableVideoChapter) Set(val *VideoChapter) {
	v.value = val
	v.isSet = true
}

func (v NullableVideoChapter) IsSet() bool {
	return v.isSet
}

func (v *NullableVideoChapter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVideoChapter(val *VideoChapter) *NullableVideoChapter {
	return &NullableVideoChapter{value: val, isSet: true}
}
