/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// Playlist struct for Playlist
type Playlist struct {
	CreatedAt    *string              `json:"created_at,omitempty"`
	Duration     *float32             `json:"duration,omitempty"`
	Id           *string              `json:"id,omitempty"`
	Iframe       *string              `json:"iframe,omitempty"`
	ItemCount    *int32               `json:"item_count,omitempty"`
	Metadata     *[]map[string]string `json:"metadata,omitempty"`
	Name         *string              `json:"name,omitempty"`
	Size         *int32               `json:"size,omitempty"`
	Tags         *[]string            `json:"tags,omitempty"`
	ThumbnailId  *string              `json:"thumbnail_id,omitempty"`
	ThumbnailUrl *string              `json:"thumbnail_url,omitempty"`
	UpdatedAt    *string              `json:"updated_at,omitempty"`
	UserId       *string              `json:"user_id,omitempty"`
	VideoItems   *[]PlaylistItem      `json:"video_items,omitempty"`
}

// NewPlaylist instantiates a new Playlist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylist() *Playlist {
	this := Playlist{}
	return &this
}

// NewPlaylistWithDefaults instantiates a new Playlist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistWithDefaults() *Playlist {
	this := Playlist{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Playlist) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Playlist) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Playlist) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *Playlist) GetDuration() float32 {
	if o == nil || o.Duration == nil {
		var ret float32
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetDurationOk() (*float32, bool) {
	if o == nil || o.Duration == nil {
		return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *Playlist) HasDuration() bool {
	if o != nil && o.Duration != nil {
		return true
	}

	return false
}

// SetDuration gets a reference to the given float32 and assigns it to the Duration field.
func (o *Playlist) SetDuration(v float32) {
	o.Duration = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Playlist) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Playlist) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Playlist) SetId(v string) {
	o.Id = &v
}

// GetIframe returns the Iframe field value if set, zero value otherwise.
func (o *Playlist) GetIframe() string {
	if o == nil || o.Iframe == nil {
		var ret string
		return ret
	}
	return *o.Iframe
}

// GetIframeOk returns a tuple with the Iframe field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetIframeOk() (*string, bool) {
	if o == nil || o.Iframe == nil {
		return nil, false
	}
	return o.Iframe, true
}

// HasIframe returns a boolean if a field has been set.
func (o *Playlist) HasIframe() bool {
	if o != nil && o.Iframe != nil {
		return true
	}

	return false
}

// SetIframe gets a reference to the given string and assigns it to the Iframe field.
func (o *Playlist) SetIframe(v string) {
	o.Iframe = &v
}

// GetItemCount returns the ItemCount field value if set, zero value otherwise.
func (o *Playlist) GetItemCount() int32 {
	if o == nil || o.ItemCount == nil {
		var ret int32
		return ret
	}
	return *o.ItemCount
}

// GetItemCountOk returns a tuple with the ItemCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetItemCountOk() (*int32, bool) {
	if o == nil || o.ItemCount == nil {
		return nil, false
	}
	return o.ItemCount, true
}

// HasItemCount returns a boolean if a field has been set.
func (o *Playlist) HasItemCount() bool {
	if o != nil && o.ItemCount != nil {
		return true
	}

	return false
}

// SetItemCount gets a reference to the given int32 and assigns it to the ItemCount field.
func (o *Playlist) SetItemCount(v int32) {
	o.ItemCount = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *Playlist) GetMetadata() []map[string]string {
	if o == nil || o.Metadata == nil {
		var ret []map[string]string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetMetadataOk() (*[]map[string]string, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *Playlist) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []map[string]string and assigns it to the Metadata field.
func (o *Playlist) SetMetadata(v []map[string]string) {
	o.Metadata = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Playlist) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Playlist) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Playlist) SetName(v string) {
	o.Name = &v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *Playlist) GetSize() int32 {
	if o == nil || o.Size == nil {
		var ret int32
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetSizeOk() (*int32, bool) {
	if o == nil || o.Size == nil {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *Playlist) HasSize() bool {
	if o != nil && o.Size != nil {
		return true
	}

	return false
}

// SetSize gets a reference to the given int32 and assigns it to the Size field.
func (o *Playlist) SetSize(v int32) {
	o.Size = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *Playlist) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *Playlist) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *Playlist) SetTags(v []string) {
	o.Tags = &v
}

// GetThumbnailId returns the ThumbnailId field value if set, zero value otherwise.
func (o *Playlist) GetThumbnailId() string {
	if o == nil || o.ThumbnailId == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailId
}

// GetThumbnailIdOk returns a tuple with the ThumbnailId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetThumbnailIdOk() (*string, bool) {
	if o == nil || o.ThumbnailId == nil {
		return nil, false
	}
	return o.ThumbnailId, true
}

// HasThumbnailId returns a boolean if a field has been set.
func (o *Playlist) HasThumbnailId() bool {
	if o != nil && o.ThumbnailId != nil {
		return true
	}

	return false
}

// SetThumbnailId gets a reference to the given string and assigns it to the ThumbnailId field.
func (o *Playlist) SetThumbnailId(v string) {
	o.ThumbnailId = &v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise.
func (o *Playlist) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetThumbnailUrlOk() (*string, bool) {
	if o == nil || o.ThumbnailUrl == nil {
		return nil, false
	}
	return o.ThumbnailUrl, true
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *Playlist) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl != nil {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given string and assigns it to the ThumbnailUrl field.
func (o *Playlist) SetThumbnailUrl(v string) {
	o.ThumbnailUrl = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Playlist) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Playlist) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Playlist) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Playlist) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Playlist) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Playlist) SetUserId(v string) {
	o.UserId = &v
}

// GetVideoItems returns the VideoItems field value if set, zero value otherwise.
func (o *Playlist) GetVideoItems() []PlaylistItem {
	if o == nil || o.VideoItems == nil {
		var ret []PlaylistItem
		return ret
	}
	return *o.VideoItems
}

// GetVideoItemsOk returns a tuple with the VideoItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Playlist) GetVideoItemsOk() (*[]PlaylistItem, bool) {
	if o == nil || o.VideoItems == nil {
		return nil, false
	}
	return o.VideoItems, true
}

// HasVideoItems returns a boolean if a field has been set.
func (o *Playlist) HasVideoItems() bool {
	if o != nil && o.VideoItems != nil {
		return true
	}

	return false
}

// SetVideoItems gets a reference to the given []PlaylistItem and assigns it to the VideoItems field.
func (o *Playlist) SetVideoItems(v []PlaylistItem) {
	o.VideoItems = &v
}

type NullablePlaylist struct {
	value *Playlist
	isSet bool
}

func (v NullablePlaylist) Get() *Playlist {
	return v.value
}

func (v *NullablePlaylist) Set(val *Playlist) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylist) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylist(val *Playlist) *NullablePlaylist {
	return &NullablePlaylist{value: val, isSet: true}
}
