/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// Watermark struct for Watermark
type Watermark struct {
	CreatedAt     *string `json:"created_at,omitempty"`
	Height        *int32  `json:"height,omitempty"`
	Id            *string `json:"id,omitempty"`
	UpdatedAt     *string `json:"updated_at,omitempty"`
	UserId        *string `json:"user_id,omitempty"`
	WatermarkName *string `json:"watermark_name,omitempty"`
	Width         *int32  `json:"width,omitempty"`
}

// NewWatermark instantiates a new Watermark object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWatermark() *Watermark {
	this := Watermark{}
	return &this
}

// NewWatermarkWithDefaults instantiates a new Watermark object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWatermarkWithDefaults() *Watermark {
	this := Watermark{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *Watermark) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *Watermark) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *Watermark) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *Watermark) GetHeight() int32 {
	if o == nil || o.Height == nil {
		var ret int32
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetHeightOk() (*int32, bool) {
	if o == nil || o.Height == nil {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *Watermark) HasHeight() bool {
	if o != nil && o.Height != nil {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int32 and assigns it to the Height field.
func (o *Watermark) SetHeight(v int32) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Watermark) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Watermark) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Watermark) SetId(v string) {
	o.Id = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *Watermark) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *Watermark) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *Watermark) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *Watermark) GetUserId() string {
	if o == nil || o.UserId == nil {
		var ret string
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetUserIdOk() (*string, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *Watermark) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given string and assigns it to the UserId field.
func (o *Watermark) SetUserId(v string) {
	o.UserId = &v
}

// GetWatermarkName returns the WatermarkName field value if set, zero value otherwise.
func (o *Watermark) GetWatermarkName() string {
	if o == nil || o.WatermarkName == nil {
		var ret string
		return ret
	}
	return *o.WatermarkName
}

// GetWatermarkNameOk returns a tuple with the WatermarkName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetWatermarkNameOk() (*string, bool) {
	if o == nil || o.WatermarkName == nil {
		return nil, false
	}
	return o.WatermarkName, true
}

// HasWatermarkName returns a boolean if a field has been set.
func (o *Watermark) HasWatermarkName() bool {
	if o != nil && o.WatermarkName != nil {
		return true
	}

	return false
}

// SetWatermarkName gets a reference to the given string and assigns it to the WatermarkName field.
func (o *Watermark) SetWatermarkName(v string) {
	o.WatermarkName = &v
}

// GetWidth returns the Width field value if set, zero value otherwise.
func (o *Watermark) GetWidth() int32 {
	if o == nil || o.Width == nil {
		var ret int32
		return ret
	}
	return *o.Width
}

// GetWidthOk returns a tuple with the Width field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Watermark) GetWidthOk() (*int32, bool) {
	if o == nil || o.Width == nil {
		return nil, false
	}
	return o.Width, true
}

// HasWidth returns a boolean if a field has been set.
func (o *Watermark) HasWidth() bool {
	if o != nil && o.Width != nil {
		return true
	}

	return false
}

// SetWidth gets a reference to the given int32 and assigns it to the Width field.
func (o *Watermark) SetWidth(v int32) {
	o.Width = &v
}

type NullableWatermark struct {
	value *Watermark
	isSet bool
}

func (v NullableWatermark) Get() *Watermark {
	return v.value
}

func (v *NullableWatermark) Set(val *Watermark) {
	v.value = val
	v.isSet = true
}

func (v NullableWatermark) IsSet() bool {
	return v.isSet
}

func (v *NullableWatermark) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWatermark(val *Watermark) *NullableWatermark {
	return &NullableWatermark{value: val, isSet: true}
}
