/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetVideoListRequest struct for GetVideoListRequest
type GetVideoListRequest struct {
	Limit    *int32      `json:"limit,omitempty"`
	Metadata *[]Metadata `json:"metadata,omitempty"`
	Offset   *int32      `json:"offset,omitempty"`
	OrderBy  *string     `json:"order_by,omitempty"`
	Search   *string     `json:"search,omitempty"`
	SortBy   *string     `json:"sort_by,omitempty"`
	Status   *string     `json:"status,omitempty"`
	Tags     *[]string   `json:"tags,omitempty"`
}

// NewGetVideoListRequest instantiates a new GetVideoListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetVideoListRequest() *GetVideoListRequest {
	this := GetVideoListRequest{}
	return &this
}

// NewGetVideoListRequestWithDefaults instantiates a new GetVideoListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetVideoListRequestWithDefaults() *GetVideoListRequest {
	this := GetVideoListRequest{}
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetLimit() int32 {
	if o == nil || o.Limit == nil {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetLimitOk() (*int32, bool) {
	if o == nil || o.Limit == nil {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasLimit() bool {
	if o != nil && o.Limit != nil {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *GetVideoListRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetMetadata() []Metadata {
	if o == nil || o.Metadata == nil {
		var ret []Metadata
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetMetadataOk() (*[]Metadata, bool) {
	if o == nil || o.Metadata == nil {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasMetadata() bool {
	if o != nil && o.Metadata != nil {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given []Metadata and assigns it to the Metadata field.
func (o *GetVideoListRequest) SetMetadata(v []Metadata) {
	o.Metadata = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetOffset() int32 {
	if o == nil || o.Offset == nil {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetOffsetOk() (*int32, bool) {
	if o == nil || o.Offset == nil {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasOffset() bool {
	if o != nil && o.Offset != nil {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetVideoListRequest) SetOffset(v int32) {
	o.Offset = &v
}

// GetOrderBy returns the OrderBy field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetOrderBy() string {
	if o == nil || o.OrderBy == nil {
		var ret string
		return ret
	}
	return *o.OrderBy
}

// GetOrderByOk returns a tuple with the OrderBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetOrderByOk() (*string, bool) {
	if o == nil || o.OrderBy == nil {
		return nil, false
	}
	return o.OrderBy, true
}

// HasOrderBy returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasOrderBy() bool {
	if o != nil && o.OrderBy != nil {
		return true
	}

	return false
}

// SetOrderBy gets a reference to the given string and assigns it to the OrderBy field.
func (o *GetVideoListRequest) SetOrderBy(v string) {
	o.OrderBy = &v
}

// GetSearch returns the Search field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetSearch() string {
	if o == nil || o.Search == nil {
		var ret string
		return ret
	}
	return *o.Search
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetSearchOk() (*string, bool) {
	if o == nil || o.Search == nil {
		return nil, false
	}
	return o.Search, true
}

// HasSearch returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasSearch() bool {
	if o != nil && o.Search != nil {
		return true
	}

	return false
}

// SetSearch gets a reference to the given string and assigns it to the Search field.
func (o *GetVideoListRequest) SetSearch(v string) {
	o.Search = &v
}

// GetSortBy returns the SortBy field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetSortBy() string {
	if o == nil || o.SortBy == nil {
		var ret string
		return ret
	}
	return *o.SortBy
}

// GetSortByOk returns a tuple with the SortBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetSortByOk() (*string, bool) {
	if o == nil || o.SortBy == nil {
		return nil, false
	}
	return o.SortBy, true
}

// HasSortBy returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasSortBy() bool {
	if o != nil && o.SortBy != nil {
		return true
	}

	return false
}

// SetSortBy gets a reference to the given string and assigns it to the SortBy field.
func (o *GetVideoListRequest) SetSortBy(v string) {
	o.SortBy = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetVideoListRequest) SetStatus(v string) {
	o.Status = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *GetVideoListRequest) GetTags() []string {
	if o == nil || o.Tags == nil {
		var ret []string
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetVideoListRequest) GetTagsOk() (*[]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetVideoListRequest) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetVideoListRequest) SetTags(v []string) {
	o.Tags = &v
}

type NullableGetVideoListRequest struct {
	value *GetVideoListRequest
	isSet bool
}

func (v NullableGetVideoListRequest) Get() *GetVideoListRequest {
	return v.value
}

func (v *NullableGetVideoListRequest) Set(val *GetVideoListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetVideoListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetVideoListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetVideoListRequest(val *GetVideoListRequest) *NullableGetVideoListRequest {
	return &NullableGetVideoListRequest{value: val, isSet: true}
}
