/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetApiKeysData struct for GetApiKeysData
type GetApiKeysData struct {
	ApiKeys *[]ApiKey `json:"api_keys,omitempty"`
	Total   *int32    `json:"total,omitempty"`
}

// NewGetApiKeysData instantiates a new GetApiKeysData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiKeysData() *GetApiKeysData {
	this := GetApiKeysData{}
	return &this
}

// NewGetApiKeysDataWithDefaults instantiates a new GetApiKeysData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiKeysDataWithDefaults() *GetApiKeysData {
	this := GetApiKeysData{}
	return &this
}

// GetApiKeys returns the ApiKeys field value if set, zero value otherwise.
func (o *GetApiKeysData) GetApiKeys() []ApiKey {
	if o == nil || o.ApiKeys == nil {
		var ret []ApiKey
		return ret
	}
	return *o.ApiKeys
}

// GetApiKeysOk returns a tuple with the ApiKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiKeysData) GetApiKeysOk() (*[]ApiKey, bool) {
	if o == nil || o.ApiKeys == nil {
		return nil, false
	}
	return o.ApiKeys, true
}

// HasApiKeys returns a boolean if a field has been set.
func (o *GetApiKeysData) HasApiKeys() bool {
	if o != nil && o.ApiKeys != nil {
		return true
	}

	return false
}

// SetApiKeys gets a reference to the given []ApiKey and assigns it to the ApiKeys field.
func (o *GetApiKeysData) SetApiKeys(v []ApiKey) {
	o.ApiKeys = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetApiKeysData) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiKeysData) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetApiKeysData) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetApiKeysData) SetTotal(v int32) {
	o.Total = &v
}

type NullableGetApiKeysData struct {
	value *GetApiKeysData
	isSet bool
}

func (v NullableGetApiKeysData) Get() *GetApiKeysData {
	return v.value
}

func (v *NullableGetApiKeysData) Set(val *GetApiKeysData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiKeysData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiKeysData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiKeysData(val *GetApiKeysData) *NullableGetApiKeysData {
	return &NullableGetApiKeysData{value: val, isSet: true}
}
