/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateLiveStreamKeyRequest struct for CreateLiveStreamKeyRequest
type CreateLiveStreamKeyRequest struct {
	Name *string `json:"name,omitempty"`
	Save *bool   `json:"save,omitempty"`
}

// NewCreateLiveStreamKeyRequest instantiates a new CreateLiveStreamKeyRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateLiveStreamKeyRequest() *CreateLiveStreamKeyRequest {
	this := CreateLiveStreamKeyRequest{}
	return &this
}

// NewCreateLiveStreamKeyRequestWithDefaults instantiates a new CreateLiveStreamKeyRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateLiveStreamKeyRequestWithDefaults() *CreateLiveStreamKeyRequest {
	this := CreateLiveStreamKeyRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CreateLiveStreamKeyRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLiveStreamKeyRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CreateLiveStreamKeyRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CreateLiveStreamKeyRequest) SetName(v string) {
	o.Name = &v
}

// GetSave returns the Save field value if set, zero value otherwise.
func (o *CreateLiveStreamKeyRequest) GetSave() bool {
	if o == nil || o.Save == nil {
		var ret bool
		return ret
	}
	return *o.Save
}

// GetSaveOk returns a tuple with the Save field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateLiveStreamKeyRequest) GetSaveOk() (*bool, bool) {
	if o == nil || o.Save == nil {
		return nil, false
	}
	return o.Save, true
}

// HasSave returns a boolean if a field has been set.
func (o *CreateLiveStreamKeyRequest) HasSave() bool {
	if o != nil && o.Save != nil {
		return true
	}

	return false
}

// SetSave gets a reference to the given bool and assigns it to the Save field.
func (o *CreateLiveStreamKeyRequest) SetSave(v bool) {
	o.Save = &v
}

type NullableCreateLiveStreamKeyRequest struct {
	value *CreateLiveStreamKeyRequest
	isSet bool
}

func (v NullableCreateLiveStreamKeyRequest) Get() *CreateLiveStreamKeyRequest {
	return v.value
}

func (v *NullableCreateLiveStreamKeyRequest) Set(val *CreateLiveStreamKeyRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateLiveStreamKeyRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateLiveStreamKeyRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateLiveStreamKeyRequest(val *CreateLiveStreamKeyRequest) *NullableCreateLiveStreamKeyRequest {
	return &NullableCreateLiveStreamKeyRequest{value: val, isSet: true}
}
