/*
 * VMS API
 *
 * VMS Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// PlaylistItem struct for PlaylistItem
type PlaylistItem struct {
	CreatedAt  *string            `json:"created_at,omitempty"`
	Id         *string            `json:"id,omitempty"`
	Next       *PlaylistItem      `json:"next,omitempty"`
	NextId     *string            `json:"next_id,omitempty"`
	PlaylistId *string            `json:"playlist_id,omitempty"`
	Previous   *PlaylistItem      `json:"previous,omitempty"`
	PreviousId *string            `json:"previous_id,omitempty"`
	UpdatedAt  *string            `json:"updated_at,omitempty"`
	Video      *PlaylistItemVideo `json:"video,omitempty"`
	VideoId    *string            `json:"video_id,omitempty"`
}

// NewPlaylistItem instantiates a new PlaylistItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaylistItem() *PlaylistItem {
	this := PlaylistItem{}
	return &this
}

// NewPlaylistItemWithDefaults instantiates a new PlaylistItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaylistItemWithDefaults() *PlaylistItem {
	this := PlaylistItem{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *PlaylistItem) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *PlaylistItem) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *PlaylistItem) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PlaylistItem) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PlaylistItem) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PlaylistItem) SetId(v string) {
	o.Id = &v
}

// GetNext returns the Next field value if set, zero value otherwise.
func (o *PlaylistItem) GetNext() PlaylistItem {
	if o == nil || o.Next == nil {
		var ret PlaylistItem
		return ret
	}
	return *o.Next
}

// GetNextOk returns a tuple with the Next field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetNextOk() (*PlaylistItem, bool) {
	if o == nil || o.Next == nil {
		return nil, false
	}
	return o.Next, true
}

// HasNext returns a boolean if a field has been set.
func (o *PlaylistItem) HasNext() bool {
	if o != nil && o.Next != nil {
		return true
	}

	return false
}

// SetNext gets a reference to the given PlaylistItem and assigns it to the Next field.
func (o *PlaylistItem) SetNext(v PlaylistItem) {
	o.Next = &v
}

// GetNextId returns the NextId field value if set, zero value otherwise.
func (o *PlaylistItem) GetNextId() string {
	if o == nil || o.NextId == nil {
		var ret string
		return ret
	}
	return *o.NextId
}

// GetNextIdOk returns a tuple with the NextId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetNextIdOk() (*string, bool) {
	if o == nil || o.NextId == nil {
		return nil, false
	}
	return o.NextId, true
}

// HasNextId returns a boolean if a field has been set.
func (o *PlaylistItem) HasNextId() bool {
	if o != nil && o.NextId != nil {
		return true
	}

	return false
}

// SetNextId gets a reference to the given string and assigns it to the NextId field.
func (o *PlaylistItem) SetNextId(v string) {
	o.NextId = &v
}

// GetPlaylistId returns the PlaylistId field value if set, zero value otherwise.
func (o *PlaylistItem) GetPlaylistId() string {
	if o == nil || o.PlaylistId == nil {
		var ret string
		return ret
	}
	return *o.PlaylistId
}

// GetPlaylistIdOk returns a tuple with the PlaylistId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetPlaylistIdOk() (*string, bool) {
	if o == nil || o.PlaylistId == nil {
		return nil, false
	}
	return o.PlaylistId, true
}

// HasPlaylistId returns a boolean if a field has been set.
func (o *PlaylistItem) HasPlaylistId() bool {
	if o != nil && o.PlaylistId != nil {
		return true
	}

	return false
}

// SetPlaylistId gets a reference to the given string and assigns it to the PlaylistId field.
func (o *PlaylistItem) SetPlaylistId(v string) {
	o.PlaylistId = &v
}

// GetPrevious returns the Previous field value if set, zero value otherwise.
func (o *PlaylistItem) GetPrevious() PlaylistItem {
	if o == nil || o.Previous == nil {
		var ret PlaylistItem
		return ret
	}
	return *o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetPreviousOk() (*PlaylistItem, bool) {
	if o == nil || o.Previous == nil {
		return nil, false
	}
	return o.Previous, true
}

// HasPrevious returns a boolean if a field has been set.
func (o *PlaylistItem) HasPrevious() bool {
	if o != nil && o.Previous != nil {
		return true
	}

	return false
}

// SetPrevious gets a reference to the given PlaylistItem and assigns it to the Previous field.
func (o *PlaylistItem) SetPrevious(v PlaylistItem) {
	o.Previous = &v
}

// GetPreviousId returns the PreviousId field value if set, zero value otherwise.
func (o *PlaylistItem) GetPreviousId() string {
	if o == nil || o.PreviousId == nil {
		var ret string
		return ret
	}
	return *o.PreviousId
}

// GetPreviousIdOk returns a tuple with the PreviousId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetPreviousIdOk() (*string, bool) {
	if o == nil || o.PreviousId == nil {
		return nil, false
	}
	return o.PreviousId, true
}

// HasPreviousId returns a boolean if a field has been set.
func (o *PlaylistItem) HasPreviousId() bool {
	if o != nil && o.PreviousId != nil {
		return true
	}

	return false
}

// SetPreviousId gets a reference to the given string and assigns it to the PreviousId field.
func (o *PlaylistItem) SetPreviousId(v string) {
	o.PreviousId = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *PlaylistItem) GetUpdatedAt() string {
	if o == nil || o.UpdatedAt == nil {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetUpdatedAtOk() (*string, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *PlaylistItem) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *PlaylistItem) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetVideo returns the Video field value if set, zero value otherwise.
func (o *PlaylistItem) GetVideo() PlaylistItemVideo {
	if o == nil || o.Video == nil {
		var ret PlaylistItemVideo
		return ret
	}
	return *o.Video
}

// GetVideoOk returns a tuple with the Video field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetVideoOk() (*PlaylistItemVideo, bool) {
	if o == nil || o.Video == nil {
		return nil, false
	}
	return o.Video, true
}

// HasVideo returns a boolean if a field has been set.
func (o *PlaylistItem) HasVideo() bool {
	if o != nil && o.Video != nil {
		return true
	}

	return false
}

// SetVideo gets a reference to the given PlaylistItemVideo and assigns it to the Video field.
func (o *PlaylistItem) SetVideo(v PlaylistItemVideo) {
	o.Video = &v
}

// GetVideoId returns the VideoId field value if set, zero value otherwise.
func (o *PlaylistItem) GetVideoId() string {
	if o == nil || o.VideoId == nil {
		var ret string
		return ret
	}
	return *o.VideoId
}

// GetVideoIdOk returns a tuple with the VideoId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaylistItem) GetVideoIdOk() (*string, bool) {
	if o == nil || o.VideoId == nil {
		return nil, false
	}
	return o.VideoId, true
}

// HasVideoId returns a boolean if a field has been set.
func (o *PlaylistItem) HasVideoId() bool {
	if o != nil && o.VideoId != nil {
		return true
	}

	return false
}

// SetVideoId gets a reference to the given string and assigns it to the VideoId field.
func (o *PlaylistItem) SetVideoId(v string) {
	o.VideoId = &v
}

type NullablePlaylistItem struct {
	value *PlaylistItem
	isSet bool
}

func (v NullablePlaylistItem) Get() *PlaylistItem {
	return v.value
}

func (v *NullablePlaylistItem) Set(val *PlaylistItem) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaylistItem) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaylistItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaylistItem(val *PlaylistItem) *NullablePlaylistItem {
	return &NullablePlaylistItem{value: val, isSet: true}
}
