/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// CreateWatermarkData struct for CreateWatermarkData
type CreateWatermarkData struct {
	CreatedAt   *string `json:"created_at,omitempty"`
	WatermarkId *string `json:"watermark_id,omitempty"`
}

// NewCreateWatermarkData instantiates a new CreateWatermarkData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateWatermarkData() *CreateWatermarkData {
	this := CreateWatermarkData{}
	return &this
}

// NewCreateWatermarkDataWithDefaults instantiates a new CreateWatermarkData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateWatermarkDataWithDefaults() *CreateWatermarkData {
	this := CreateWatermarkData{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CreateWatermarkData) GetCreatedAt() string {
	if o == nil || o.CreatedAt == nil {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWatermarkData) GetCreatedAtOk() (*string, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CreateWatermarkData) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CreateWatermarkData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetWatermarkId returns the WatermarkId field value if set, zero value otherwise.
func (o *CreateWatermarkData) GetWatermarkId() string {
	if o == nil || o.WatermarkId == nil {
		var ret string
		return ret
	}
	return *o.WatermarkId
}

// GetWatermarkIdOk returns a tuple with the WatermarkId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateWatermarkData) GetWatermarkIdOk() (*string, bool) {
	if o == nil || o.WatermarkId == nil {
		return nil, false
	}
	return o.WatermarkId, true
}

// HasWatermarkId returns a boolean if a field has been set.
func (o *CreateWatermarkData) HasWatermarkId() bool {
	if o != nil && o.WatermarkId != nil {
		return true
	}

	return false
}

// SetWatermarkId gets a reference to the given string and assigns it to the WatermarkId field.
func (o *CreateWatermarkData) SetWatermarkId(v string) {
	o.WatermarkId = &v
}

type NullableCreateWatermarkData struct {
	value *CreateWatermarkData
	isSet bool
}

func (v NullableCreateWatermarkData) Get() *CreateWatermarkData {
	return v.value
}

func (v *NullableCreateWatermarkData) Set(val *CreateWatermarkData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateWatermarkData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateWatermarkData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateWatermarkData(val *CreateWatermarkData) *NullableCreateWatermarkData {
	return &NullableCreateWatermarkData{value: val, isSet: true}
}
