/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetLiveStreamVideoResponse struct for GetLiveStreamVideoResponse
type GetLiveStreamVideoResponse struct {
	Data   *LiveStreamVideoResponse `json:"data,omitempty"`
	Status *string                  `json:"status,omitempty"`
}

// NewGetLiveStreamVideoResponse instantiates a new GetLiveStreamVideoResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLiveStreamVideoResponse() *GetLiveStreamVideoResponse {
	this := GetLiveStreamVideoResponse{}
	return &this
}

// NewGetLiveStreamVideoResponseWithDefaults instantiates a new GetLiveStreamVideoResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLiveStreamVideoResponseWithDefaults() *GetLiveStreamVideoResponse {
	this := GetLiveStreamVideoResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLiveStreamVideoResponse) GetData() LiveStreamVideoResponse {
	if o == nil || o.Data == nil {
		var ret LiveStreamVideoResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamVideoResponse) GetDataOk() (*LiveStreamVideoResponse, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLiveStreamVideoResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given LiveStreamVideoResponse and assigns it to the Data field.
func (o *GetLiveStreamVideoResponse) SetData(v LiveStreamVideoResponse) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetLiveStreamVideoResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLiveStreamVideoResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetLiveStreamVideoResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetLiveStreamVideoResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetLiveStreamVideoResponse struct {
	value *GetLiveStreamVideoResponse
	isSet bool
}

func (v NullableGetLiveStreamVideoResponse) Get() *GetLiveStreamVideoResponse {
	return v.value
}

func (v *NullableGetLiveStreamVideoResponse) Set(val *GetLiveStreamVideoResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLiveStreamVideoResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLiveStreamVideoResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLiveStreamVideoResponse(val *GetLiveStreamVideoResponse) *NullableGetLiveStreamVideoResponse {
	return &NullableGetLiveStreamVideoResponse{value: val, isSet: true}
}
