/*
 * W3STREAM API
 *
 * W3STREAM Service
 *
 * API version: 1.0
 * Contact: support@swagger.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package w3streamsdk

import (
//"encoding/json"
)

// GetPlaylistListResponse struct for GetPlaylistListResponse
type GetPlaylistListResponse struct {
	Data   *GetPlaylistListData `json:"data,omitempty"`
	Status *string              `json:"status,omitempty"`
}

// NewGetPlaylistListResponse instantiates a new GetPlaylistListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPlaylistListResponse() *GetPlaylistListResponse {
	this := GetPlaylistListResponse{}
	return &this
}

// NewGetPlaylistListResponseWithDefaults instantiates a new GetPlaylistListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPlaylistListResponseWithDefaults() *GetPlaylistListResponse {
	this := GetPlaylistListResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPlaylistListResponse) GetData() GetPlaylistListData {
	if o == nil || o.Data == nil {
		var ret GetPlaylistListData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListResponse) GetDataOk() (*GetPlaylistListData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPlaylistListResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given GetPlaylistListData and assigns it to the Data field.
func (o *GetPlaylistListResponse) SetData(v GetPlaylistListData) {
	o.Data = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetPlaylistListResponse) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPlaylistListResponse) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetPlaylistListResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetPlaylistListResponse) SetStatus(v string) {
	o.Status = &v
}

type NullableGetPlaylistListResponse struct {
	value *GetPlaylistListResponse
	isSet bool
}

func (v NullableGetPlaylistListResponse) Get() *GetPlaylistListResponse {
	return v.value
}

func (v *NullableGetPlaylistListResponse) Set(val *GetPlaylistListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPlaylistListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPlaylistListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPlaylistListResponse(val *GetPlaylistListResponse) *NullableGetPlaylistListResponse {
	return &NullableGetPlaylistListResponse{value: val, isSet: true}
}
